# permissions for end users to view btmagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: btmagent-viewer-role
rules:
- apiGroups:
  - apm.egapm
  resources:
  - btmagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apm.egapm
  resources:
  - btmagents/status
  verbs:
  - get
