# permissions for end users to edit btmagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: btmagent-editor-role
rules:
- apiGroups:
  - apm.egapm
  resources:
  - btmagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apm.egapm
  resources:
  - btmagents/status
  verbs:
  - get
