apiVersion: apm.egapm/v1
kind: BtmAgent
metadata:
  name: btmagent-sample
spec:
  monitoredNamespaces:
    - default
    - petclinic
  unMonitoredNamespaces:
    - egagent
  matchingLabels:
    - enablemwc
